import { Listing, TruckType } from '../types';

// Helper to create recent timestamps (0-4 hours ago)
const getRecentTime = (hoursAgo: number) => Date.now() - (hoursAgo * 60 * 60 * 1000);
const getExpiry = () => Date.now() + (72 * 60 * 60 * 1000); // +3 days

// Helper for realistic IDs
const rId = () => Math.random().toString(36).substr(2, 9);

export const MOCK_LISTINGS: Listing[] = [
  // --- TRUCKS (Mix of KZ, UZ, RU, KG) ---
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(0.5),
    expiresAt: getExpiry(),
    contactName: 'Бахтияр Транс',
    contactPhone: '+77771234567',
    telegramHandle: 'bahti_trans',
    fromCity: 'Алматы',
    toCity: 'Ташкент',
    truckType: TruckType.TENT,
    capacity: 22,
    date: 'Завтра',
    urgent: true,
    isEmpty: true,
    comment: 'Еду пустой, возьму любой груз. Документы в порядке.',
    createdAt: getRecentTime(0.5) // 30 mins ago
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(1.2),
    expiresAt: getExpiry(),
    contactName: 'Сергей (ИП)',
    contactPhone: '+79008889900',
    fromCity: 'Москва',
    toCity: 'Бишкек',
    truckType: TruckType.REF,
    capacity: 20,
    date: 'Сегодня',
    urgent: true,
    isEmpty: true,
    comment: 'Реф -18. Срочно ищу загрузку на обратку.',
    createdAt: getRecentTime(1.2)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(2),
    expiresAt: getExpiry(),
    contactName: 'Ойбек',
    contactPhone: '+998901112233',
    fromCity: 'Самарканд',
    toCity: 'Шымкент',
    truckType: TruckType.BOARD,
    capacity: 10,
    date: 'Сегодня',
    urgent: false,
    isEmpty: true,
    createdAt: getRecentTime(2)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(3.5),
    expiresAt: getExpiry(),
    contactName: 'ТрансЛогистик',
    contactPhone: '+77019998877',
    fromCity: 'Астана',
    toCity: 'Екатеринбург',
    truckType: TruckType.MEGA,
    capacity: 22,
    date: 'В ближайшее время',
    urgent: false,
    isEmpty: false,
    createdAt: getRecentTime(3.5)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(4),
    expiresAt: getExpiry(),
    contactName: 'Марат',
    contactPhone: '+996555123123',
    fromCity: 'Бишкек',
    toCity: 'Ош',
    truckType: TruckType.CONTAINER,
    capacity: 25,
    date: 'Завтра',
    urgent: true,
    isEmpty: true,
    createdAt: getRecentTime(4)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(5),
    expiresAt: getExpiry(),
    contactName: 'Алексей',
    contactPhone: '+79261234567',
    fromCity: 'Казань',
    toCity: 'Москва',
    truckType: TruckType.TENT,
    capacity: 20,
    date: 'Сегодня',
    urgent: true,
    isEmpty: true,
    comment: 'Стою на выгрузке, готов стартовать вечером.',
    createdAt: getRecentTime(5)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(6),
    expiresAt: getExpiry(),
    contactName: 'Азамат',
    contactPhone: '+77785554433',
    fromCity: 'Актау',
    toCity: 'Атырау',
    truckType: TruckType.TANKER,
    capacity: 30,
    date: '28.10',
    urgent: false,
    isEmpty: true,
    createdAt: getRecentTime(6)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(8),
    expiresAt: getExpiry(),
    contactName: 'Logos Group',
    contactPhone: '+998991234567',
    fromCity: 'Ташкент',
    toCity: 'Бухара',
    truckType: TruckType.TENT,
    capacity: 5,
    date: 'Сегодня',
    urgent: false,
    isEmpty: true,
    createdAt: getRecentTime(8)
  },

  // --- CARGO ---
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(0.2),
    expiresAt: getExpiry(),
    contactName: 'ООО СтройСнаб',
    contactPhone: '+79998887766',
    fromCity: 'Новосибирск',
    toCity: 'Алматы',
    weight: 20,
    volume: 82,
    cargoType: 'Стройматериалы',
    price: 800000,
    currency: 'KZT',
    neededTruckTypes: ['Тент', 'Борт'],
    hasPrepayment: true,
    urgent: true,
    date: 'Срочно',
    createdAt: getRecentTime(0.2)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(0.8),
    expiresAt: getExpiry(),
    contactName: 'Ирина (Частник)',
    contactPhone: '+79005554433',
    fromCity: 'Москва',
    toCity: 'Минск',
    weight: 1.5,
    cargoType: 'Личные вещи',
    neededTruckTypes: ['Мега'],
    tags: ['dogruz'],
    currency: 'RUB',
    urgent: true,
    date: 'Сегодня',
    comment: 'Нужна аккуратная погрузка, 2 грузчика',
    createdAt: getRecentTime(0.8)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(1.5),
    expiresAt: getExpiry(),
    contactName: 'AgroExport',
    contactPhone: '+998901239876',
    fromCity: 'Фергана',
    toCity: 'Москва',
    weight: 20,
    cargoType: 'Фрукты (Виноград)',
    neededTruckTypes: ['Рефрижератор'],
    hasPrepayment: true,
    price: 3500,
    currency: 'USD',
    urgent: true,
    date: 'Сегодня',
    createdAt: getRecentTime(1.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(3),
    expiresAt: getExpiry(),
    contactName: 'Темир Металл',
    contactPhone: '+77021112233',
    fromCity: 'Караганда',
    toCity: 'Астана',
    weight: 15,
    cargoType: 'Металлопрокат',
    neededTruckTypes: ['Борт', 'Площадка'],
    currency: 'KZT',
    urgent: false,
    date: 'Завтра',
    createdAt: getRecentTime(3)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(4.5),
    expiresAt: getExpiry(),
    contactName: 'Дмитрий',
    contactPhone: '+79161231234',
    fromCity: 'Санкт-Петербург',
    toCity: 'Псков',
    weight: 3,
    volume: 15,
    cargoType: 'Мебель',
    neededTruckTypes: ['Тент'],
    tags: ['dogruz'],
    price: 15000,
    currency: 'RUB',
    urgent: false,
    date: '30.10',
    createdAt: getRecentTime(4.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(6),
    expiresAt: getExpiry(),
    contactName: 'Алишер',
    contactPhone: '+996700123456',
    fromCity: 'Джалал-Абад',
    toCity: 'Бишкек',
    weight: 5,
    cargoType: 'Текстиль',
    neededTruckTypes: ['Тент'],
    hasPrepayment: false,
    urgent: false,
    date: 'Завтра',
    createdAt: getRecentTime(6),
    currency: 'KGS'
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(7),
    expiresAt: getExpiry(),
    contactName: 'TechImport',
    contactPhone: '+77272223344',
    fromCity: 'Алматы',
    toCity: 'Уральск',
    weight: 0.5,
    cargoType: 'Электроника',
    neededTruckTypes: ['Тент', 'Контейнер'],
    tags: ['dogruz'],
    price: 50000,
    currency: 'KZT',
    urgent: true,
    date: 'Сегодня',
    createdAt: getRecentTime(7)
  }
];