

import { Listing, TruckType } from '../types';

// Helper to create recent timestamps (0-24 hours ago)
const getRecentTime = (hoursAgo: number) => Date.now() - (hoursAgo * 60 * 60 * 1000);
const getExpiry = () => Date.now() + (72 * 60 * 60 * 1000); // +3 days

// Helper for realistic IDs (prefixed to avoid collision with real DB)
const rId = () => 'mock_' + Math.random().toString(36).substr(2, 9);

export const MOCK_LISTINGS: Listing[] = [
  // --- 10 TRUCKS (UZBEKISTAN CENTERED) ---
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(0.5),
    expiresAt: getExpiry(),
    contactName: 'Jamshid Trans',
    contactPhone: '+998901234567',
    telegramHandle: 'jamshid_logist',
    fromCity: 'Toshkent',
    toCity: 'Moskva',
    truckType: TruckType.REF,
    capacity: 20,
    date: 'Bugun',
    urgent: true,
    isEmpty: true,
    comment: 'Ref -18. Hujjatlar tayyor, tez yuraman.',
    createdAt: getRecentTime(0.5)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(1.5),
    expiresAt: getExpiry(),
    contactName: 'Otabek',
    contactPhone: '+998935554433',
    fromCity: 'Samarqand',
    toCity: 'Buxoro',
    truckType: TruckType.TENT,
    capacity: 10,
    date: 'Ertaga',
    urgent: false,
    isEmpty: true,
    comment: 'Tent 86 kub. To\'lov naqd.',
    createdAt: getRecentTime(1.5)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(2),
    expiresAt: getExpiry(),
    contactName: 'Murod Aka',
    contactPhone: '+998971112233',
    fromCity: 'Andijon',
    toCity: 'Toshkent',
    truckType: TruckType.BOARD,
    capacity: 5,
    date: 'Hozir',
    urgent: true,
    isEmpty: true,
    comment: 'Bort, ochiq. Vodiy bo\'ylab.',
    createdAt: getRecentTime(2)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(3),
    expiresAt: getExpiry(),
    contactName: 'Silk Road Logistics',
    contactPhone: '+998998889988',
    fromCity: 'Toshkent',
    toCity: 'Olmaota',
    truckType: TruckType.MEGA,
    capacity: 22,
    date: '28.02',
    urgent: false,
    isEmpty: true,
    createdAt: getRecentTime(3)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(4),
    expiresAt: getExpiry(),
    contactName: 'Azizbek',
    contactPhone: '+998912223344',
    fromCity: 'Urganch',
    toCity: 'Xiva',
    truckType: TruckType.ISOTHERM,
    capacity: 3,
    date: 'Bugun',
    urgent: false,
    isEmpty: true,
    createdAt: getRecentTime(4)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(5),
    expiresAt: getExpiry(),
    contactName: 'Sherzod',
    contactPhone: '+998909998877',
    fromCity: 'Termiz',
    toCity: 'Qarshi',
    truckType: TruckType.GRAIN,
    capacity: 25,
    date: 'Ertaga',
    urgent: true,
    isEmpty: true,
    comment: 'Zernovoz. Bo\'shman.',
    createdAt: getRecentTime(5)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(6),
    expiresAt: getExpiry(),
    contactName: 'Farhod',
    contactPhone: '+998941231234',
    fromCity: 'Namangan',
    toCity: 'Bishkek',
    truckType: TruckType.TENT,
    capacity: 20,
    date: 'Bugun kechga',
    urgent: true,
    isEmpty: true,
    createdAt: getRecentTime(6)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(7),
    expiresAt: getExpiry(),
    contactName: 'Alisher',
    contactPhone: '+998930001122',
    fromCity: 'Nukus',
    toCity: 'Qo\'ng\'irot',
    truckType: TruckType.TANKER,
    capacity: 30,
    date: 'Kelishilgan',
    urgent: false,
    isEmpty: true,
    createdAt: getRecentTime(7)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(8),
    expiresAt: getExpiry(),
    contactName: 'Bekzod',
    contactPhone: '+998997776655',
    fromCity: 'Jizzax',
    toCity: 'Sirdaryo',
    truckType: TruckType.PLATFORM,
    capacity: 15,
    date: 'Ertaga',
    urgent: false,
    isEmpty: true,
    comment: 'Ploshadka, truba olaman.',
    createdAt: getRecentTime(8)
  },
  {
    id: rId(),
    kind: 'truck',
    status: 'active',
    updatedAt: getRecentTime(9),
    expiresAt: getExpiry(),
    contactName: 'Sardor Logistic',
    contactPhone: '+998981234567',
    fromCity: 'Toshkent',
    toCity: 'Istanbul',
    truckType: TruckType.TENT,
    capacity: 22,
    date: 'Hafta oxiri',
    urgent: true,
    isEmpty: true,
    comment: 'Tir, Cmr bor. Viza bor.',
    createdAt: getRecentTime(9)
  },

  // --- 10 CARGO (UZBEKISTAN CENTERED) ---
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(0.2),
    expiresAt: getExpiry(),
    contactName: 'Agro Export LLC',
    contactPhone: '+998901110011',
    fromCity: 'Farg\'ona',
    toCity: 'Moskva',
    weight: 20,
    volume: 82,
    cargoType: 'Mevalar (Uzum)',
    price: 3500,
    currency: 'USD',
    neededTruckTypes: ['Рефрижератор'],
    hasPrepayment: true,
    urgent: true,
    date: 'Bugun',
    comment: 'Ref kerak, +4 gradus.',
    createdAt: getRecentTime(0.2)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(1),
    expiresAt: getExpiry(),
    contactName: 'Akmal',
    contactPhone: '+998932223322',
    fromCity: 'Toshkent',
    toCity: 'Samarqand',
    weight: 5,
    cargoType: 'Mebel',
    neededTruckTypes: ['TENT', 'BORT'],
    tags: ['dogruz'],
    price: 1500000,
    currency: 'UZS',
    urgent: true,
    date: 'Hozir',
    createdAt: getRecentTime(1)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(2.5),
    expiresAt: getExpiry(),
    contactName: 'Texno Market',
    contactPhone: '+998973334455',
    fromCity: 'Navoiy',
    toCity: 'Toshkent',
    weight: 10,
    cargoType: 'Maishiy texnika',
    neededTruckTypes: ['Tent', 'Izoterm'],
    currency: 'UZS',
    urgent: false,
    date: 'Ertaga',
    createdAt: getRecentTime(2.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(3.5),
    expiresAt: getExpiry(),
    contactName: 'Bahrom',
    contactPhone: '+998991231234',
    fromCity: 'Buxoro',
    toCity: 'Xiva',
    weight: 2,
    cargoType: 'Gilamlar',
    neededTruckTypes: ['Tent'],
    tags: ['dogruz'],
    price: 500000,
    currency: 'UZS',
    urgent: true,
    date: 'Bugun',
    createdAt: getRecentTime(3.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(4.5),
    expiresAt: getExpiry(),
    contactName: 'Stroy Materialy',
    contactPhone: '+998905556677',
    fromCity: 'Angren',
    toCity: 'Toshkent',
    weight: 22,
    cargoType: 'Sement',
    neededTruckTypes: ['Bort', 'Tent'],
    hasPrepayment: false,
    urgent: true,
    currency: 'UZS',
    date: 'Ertaga ertalab',
    createdAt: getRecentTime(4.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(5.5),
    expiresAt: getExpiry(),
    contactName: 'Textile Group',
    contactPhone: '+998917778899',
    fromCity: 'Namangan',
    toCity: 'Bishkek',
    weight: 8,
    cargoType: 'Trikomtaj',
    neededTruckTypes: ['Tent'],
    currency: 'USD',
    urgent: false,
    date: 'Hafta ichida',
    createdAt: getRecentTime(5.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(6.5),
    expiresAt: getExpiry(),
    contactName: 'Umidjon',
    contactPhone: '+998930009988',
    fromCity: 'Qarshi',
    toCity: 'Termiz',
    weight: 15,
    cargoType: 'Un mahsulotlari',
    neededTruckTypes: ['Tent', 'Zernovoz'],
    price: 3000000,
    currency: 'UZS',
    urgent: true,
    date: 'Bugun',
    createdAt: getRecentTime(6.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(7.5),
    expiresAt: getExpiry(),
    contactName: 'Auto Parts',
    contactPhone: '+998991112211',
    fromCity: 'Toshkent',
    toCity: 'Nukus',
    weight: 1,
    cargoType: 'Zapchastlar',
    neededTruckTypes: ['Tent'],
    tags: ['dogruz'],
    urgent: true,
    currency: 'UZS',
    date: 'Tezroq',
    createdAt: getRecentTime(7.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(8.5),
    expiresAt: getExpiry(),
    contactName: 'Dilshod',
    contactPhone: '+998904445566',
    fromCity: 'Guliston',
    toCity: 'Jizzax',
    weight: 6,
    cargoType: 'Poliz ekinlari',
    neededTruckTypes: ['Bort'],
    currency: 'UZS',
    urgent: false,
    date: 'Ertaga',
    createdAt: getRecentTime(8.5)
  },
  {
    id: rId(),
    kind: 'cargo',
    status: 'active',
    updatedAt: getRecentTime(9.5),
    expiresAt: getExpiry(),
    contactName: 'Global Trade',
    contactPhone: '+998951234567',
    fromCity: 'Toshkent',
    toCity: 'Ostona',
    weight: 20,
    cargoType: 'Konserva',
    neededTruckTypes: ['Tent', 'Ref'],
    price: 1200,
    currency: 'USD',
    urgent: true,
    date: '29.02',
    createdAt: getRecentTime(9.5)
  }
];
